[build]
    command = "npm run build"
    functions = "functions/"
    publish = "build"

[functions]
  external_node_modules = ["express","serverless-http"]
  node_bundler = "esbuild"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true