name: 'Deploy on netlify'

on:
  push:
    branches:
      - main
      - feat/test-express

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: npm run build
      - name: Deploying on netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          github-token: ${{ secrets.GT_TOKEN }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: './build'
          functions_directory: 'netlify/functions/'
          comment-on-commit: true
